# Generated by Django 5.1.3 on 2024-11-26 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TertuliaForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('numero_telefono', models.CharField(blank=True, max_length=12)),
                ('nombre_tertulia', models.CharField(max_length=150)),
                ('tertulia_folio_id', models.IntegerField()),
            ],
        ),
    ]
